import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :muddle, MuddleWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# TLS termination + the http → https redirect happen at the Traefik
# ingress, so Phoenix doesn't run `force_ssl` itself. Leaving it on
# behind a proxy that doesn't reliably forward `X-Forwarded-Proto`
# breaks the LiveView WebSocket: Plug.SSL sees the upgrade as plain
# HTTP, returns a 301, and the browser drops the connection.
#
# If you ever serve directly without a TLS-terminating proxy, re-enable
# this block:
#
#     config :muddle, MuddleWeb.Endpoint,
#       force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
